from __future__ import annotations

import argparse
import csv
import json
import signal
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.pipeline import CivicRAGPipeline


DEFAULT_INPUT = PROJECT_ROOT / "docs/evaluation/collected_faq_pairs_2026_06_09/collected_faq_pairs_corrected_expected_sources.json"
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "docs/evaluation/collected_faq_pairs_2026_06_09/actual_chatbot_answers"
DEFAULT_CONFIG = PROJECT_ROOT / "domains/birth_death_registration/config.json"


class AnswerTimeoutError(RuntimeError):
    pass


def ask_with_timeout(
    pipeline: CivicRAGPipeline,
    query: str,
    *,
    model: str,
    method: str,
    timeout_seconds: int,
) -> dict[str, Any]:
    def handle_timeout(signum: int, frame: Any) -> None:
        raise AnswerTimeoutError(f"answer generation exceeded {timeout_seconds} seconds")

    previous_handler = signal.signal(signal.SIGALRM, handle_timeout)
    signal.alarm(timeout_seconds)
    try:
        return pipeline.ask(query, model=model, method=method)
    finally:
        signal.alarm(0)
        signal.signal(signal.SIGALRM, previous_handler)


def load_cases(path: Path) -> list[dict[str, Any]]:
    records = json.loads(path.read_text(encoding="utf-8"))
    cases: list[dict[str, Any]] = []
    for record in records:
        variants = [
            ("curated_question", str(record.get("question", "")).strip()),
            ("original_question", str(record.get("original_question", "")).strip()),
        ]
        for variant, query in variants:
            if not query:
                continue
            cases.append(
                {
                    "case_id": f"{record['chunk_id']}::{variant}",
                    "chunk_id": record["chunk_id"],
                    "provided_chunk_id": record.get("provided_chunk_id", record["chunk_id"]),
                    "source_label_corrected": bool(record.get("source_label_corrected")),
                    "category": record.get("category", ""),
                    "variant": variant,
                    "query": query,
                    "expected_answer": str(record.get("answer", "")).strip(),
                }
            )
    return cases


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def write_report(path: Path, rows: list[dict[str, Any]], *, models: list[str], method: str) -> None:
    lines = [
        "# Collected FAQ Actual Civic.ai Answers",
        "",
        f"Generated: {datetime.now().isoformat(timespec='seconds')}",
        f"Method: `{method}`",
        f"Models requested: `{', '.join(models)}`",
        "",
        "Important note: this report contains the actual backend answer returned by `pipeline.ask(...)`, which is the same Civic.ai logic used by the local chatbot. These answers can be worse than retrieval metrics if the LLM receives imperfectly ranked evidence; that is why this report is useful.",
        "",
        "## Run Summary",
        "",
        "| Model | Cases | Completed | Timed out / Error | Mean elapsed seconds |",
        "|---|---:|---:|---:|---:|",
    ]
    for model in models:
        model_rows = [row for row in rows if row["model"] == model]
        completed = [row for row in model_rows if not row["error"]]
        errored = [row for row in model_rows if row["error"]]
        mean_elapsed = sum(float(row["elapsed_seconds"]) for row in model_rows) / len(model_rows) if model_rows else 0.0
        lines.append(f"| {model} | {len(model_rows)} | {len(completed)} | {len(errored)} | {mean_elapsed:.2f} |")

    for row in rows:
        lines.extend(
            [
                "",
                f"## {row['case_id']} | {row['model']}",
                "",
                f"Category: `{row['category']}`",
                f"Variant: `{row['variant']}`",
                f"Generated by: `{row['method_label']} + {row['model']}`",
                f"Elapsed seconds: `{row['elapsed_seconds']}`",
            ]
        )
        if row["source_label_corrected"] == "1":
            lines.append(f"Source-label audit: provided `{row['provided_chunk_id']}` was corrected to `{row['chunk_id']}`.")
        if row["error"]:
            lines.extend(["", f"Error: `{row['error']}`"])
        lines.extend(
            [
                "",
                "### Question",
                "",
                row["query"],
                "",
                "### Expected Reference Answer",
                "",
                row["expected_answer"],
                "",
                "### Actual Civic.ai Answer",
                "",
                row["actual_answer"] or "(No answer returned.)",
                "",
                "### Sources Returned",
                "",
            ]
        )
        for index, source_id in enumerate(row["source_ids"].split(";") if row["source_ids"] else [], start=1):
            lines.append(f"{index}. `{source_id}`")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Run collected FAQ questions through the actual Civic.ai answer path.")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--models", nargs="+", default=["llama3.2"])
    parser.add_argument("--method", choices=["civic", "simple"], default="civic")
    parser.add_argument("--timeout-seconds", type=int, default=120)
    parser.add_argument("--limit", type=int, default=0)
    args = parser.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)
    cases = load_cases(args.input)
    if args.limit:
        cases = cases[: args.limit]
    pipeline = CivicRAGPipeline(PROJECT_ROOT, DEFAULT_CONFIG)

    rows: list[dict[str, Any]] = []
    csv_path = args.output_dir / "actual_chatbot_answers.csv"
    report_path = args.output_dir / "actual_chatbot_answers.md"

    for model in args.models:
        for index, case in enumerate(cases, start=1):
            print(f"[{model}] {index}/{len(cases)} {case['case_id']}", flush=True)
            started = time.perf_counter()
            error = ""
            response: dict[str, Any] = {"answer": "", "sources": []}
            try:
                response = ask_with_timeout(
                    pipeline,
                    case["query"],
                    model=model,
                    method=args.method,
                    timeout_seconds=args.timeout_seconds,
                )
            except Exception as exc:
                error = str(exc)
            elapsed = round(time.perf_counter() - started, 2)
            source_ids = [str(source["id"]) for source in response.get("sources", [])]
            rows.append(
                {
                    "model": model,
                    "method": args.method,
                    "method_label": "CivicRAG (ours)" if args.method == "civic" else "Simple RAG",
                    "case_id": case["case_id"],
                    "chunk_id": case["chunk_id"],
                    "provided_chunk_id": case["provided_chunk_id"],
                    "source_label_corrected": int(case["source_label_corrected"]),
                    "category": case["category"],
                    "variant": case["variant"],
                    "query": case["query"],
                    "expected_answer": case["expected_answer"],
                    "actual_answer": str(response.get("answer", "")).strip(),
                    "source_ids": ";".join(source_ids),
                    "elapsed_seconds": elapsed,
                    "error": error,
                }
            )
            write_csv(csv_path, rows)
            write_report(report_path, rows, models=args.models, method=args.method)

    print(f"Wrote: {csv_path}")
    print(f"Wrote: {report_path}")


if __name__ == "__main__":
    main()
